module.exports = {
  pages: [
    "pages/component/index",
    // "pages/component/view/view",
    // "pages/component/scroll-view/scroll-view",
    // "pages/component/swiper/swiper",
    // "pages/component/text/text",
    // "pages/component/icon/icon",
    // "pages/component/progress/progress",
    // "pages/component/button/button",
    // "pages/component/checkbox/checkbox",
    // "pages/component/form/form",
    // "pages/component/input/input",
    // "pages/component/label/label",
    // "pages/component/picker/picker",
    // "pages/component/radio/radio",
    // "pages/component/slider/slider",
    // "pages/component/switch/switch",
    // "pages/component/textarea/textarea",
    // "pages/component/navigator/navigator",
    // "pages/component/navigator/navigate",
    // "pages/component/navigator/redirect",
    // "pages/component/image/image",
    // "pages/component/audio/audio",
    // "pages/component/video/video",
    // "pages/component/map/map",
    // "pages/component/canvas/canvas",
    // "pages/component/ad/ad",
    // "pages/component/movable-view/movable-view",
    // "pages/component/cover-view/cover-view",
    // "pages/component/rich-text/rich-text",
    // "pages/component/picker-view/picker-view",
    // "pages/component/camera/camera",
    // "pages/component/camera-scan-code/camera-scan-code",
    // "pages/component/open-data/open-data",
    // "pages/component/web-view/web-view",
    // "pages/component/map-styles/map-styles",
    // "pages/component/doc-web-view/doc-web-view",
    // "pages/component/editor/editor",
    "pages/api/index",
    // "pages/api/login/login",
    // "pages/api/get-user-info/get-user-info",
    // "pages/api/request-payment/request-payment",
    // "pages/api/share/share",
    // "pages/api/share-button/share-button",
    // "pages/api/custom-message/custom-message",
    // "pages/api/template-message/template-message",
    // "pages/api/set-navigation-bar-title/set-navigation-bar-title",
    // "pages/api/navigation-bar-loading/navigation-bar-loading",
    // "pages/api/navigator/navigator",
    // "pages/api/pull-down-refresh/pull-down-refresh",
    // "pages/api/animation/animation",
    // "pages/api/action-sheet/action-sheet",
    // "pages/api/modal/modal",
    // "pages/api/toast/toast",
    // "pages/api/get-network-type/get-network-type",
    // "pages/api/on-network-status-change/on-network-status-change",
    // "pages/api/get-system-info/get-system-info",
    // "pages/api/on-compass-change/on-compass-change",
    // "pages/api/make-phone-call/make-phone-call",
    // "pages/api/scan-code/scan-code",
    // "pages/api/request/request",
    // "pages/api/web-socket/web-socket",
    // "pages/api/upload-file/upload-file",
    // "pages/api/download-file/download-file",
    // "pages/api/image/image",
    // "pages/api/voice/voice",
    // "pages/api/file/file",
    // "pages/api/on-accelerometer-change/on-accelerometer-change",
    // "pages/api/canvas/canvas",
    // "pages/api/background-audio/background-audio",
    // "pages/api/video/video",
    // "pages/api/get-location/get-location",
    // "pages/api/open-location/open-location",
    // "pages/api/choose-location/choose-location",
    // "pages/api/storage/storage",
    // "pages/api/get-wxml-node-info/get-wxml-node-info",
    // "pages/api/load-font-face/load-font-face",
    // "pages/api/clipboard-data/clipboard-data",
    // "pages/api/bluetooth/bluetooth",
    // "pages/api/screen-brightness/screen-brightness",
    // "pages/api/vibrate/vibrate",
    // "pages/api/add-contact/add-contact",
    // "pages/api/wifi/wifi",
    // "pages/api/page-scroll/page-scroll",
    // "pages/api/intersection-observer/intersection-observer",
    // "pages/api/capture-screen/capture-screen",
    // "pages/api/worker/worker",
    // "pages/api/ibeacon/ibeacon",
    // "pages/api/choose-address/choose-address",
    // "pages/api/setting/setting",
    // "pages/api/choose-invoice-title/choose-invoice-title",
    // "pages/api/soter-authentication/soter-authentication",
    // "pages/api/doc-web-view/doc-web-view",
    "pages/cloud/index",
    // "pages/cloud/user-authentication/user-authentication",
    // "pages/cloud/get-wx-context/get-wx-context",
    // "pages/cloud/upload-file/upload-file",
    // "pages/cloud/download-file/download-file",
    // "pages/cloud/get-temp-file-url/get-temp-file-url",
    // "pages/cloud/delete-file/delete-file",
    // "pages/cloud/cloud-file-component/cloud-file-component",
    // "pages/cloud/crud/crud",
    // "pages/cloud/crud-detail/crud-detail",
    // "pages/cloud/db-permission/db-permission",
    // "pages/cloud/server-date/server-date",
    // "pages/cloud/scf-database/scf-database",
    // "pages/cloud/scf-storage/scf-storage",
    // "pages/cloud/scf-openapi/scf-openapi",
    // "pages/cloud/doc-web-view/doc-web-view",
    "pages/weui/index",
    // "pages/weui/cell/cell",
    // "pages/weui/slideview/slideview",
    // "pages/weui/form/form",
    // "pages/weui/uploader/uploader",
    "pages/weui/pages/article/index",
    // "pages/weui/badge/badge",
    // "pages/weui/flex/flex",
    // "pages/weui/footer/footer",
    // "pages/weui/gallery/gallery",
    // "pages/weui/grid/grid",
    // "pages/weui/loadmore/loadmore",
    // "pages/weui/loading/loading",
    // "pages/weui/panel/panel",
    // "pages/weui/preview/preview",
    // "pages/weui/dialog/dialog",
    // "pages/weui/msg/msg",
    // "pages/weui/msg/msg_text",
    // "pages/weui/msg/msg_text_primary",
    // "pages/weui/msg/msg_success",
    // "pages/weui/msg/msg_fail",
    // "pages/weui/navbar/navbar",
    // "pages/weui/navigation/navigation",
    // "pages/weui/tabbar/tabbar",
    // "pages/weui/icons/icons",
    // "pages/weui/form-page/form-page",
    // "pages/weui/half-screen-dialog/half-screen-dialog",
    "pages/weui/pages/actionsheet/index"
  ],
  window: {
    navigationBarTextStyle: "black",
    navigationBarTitleText: "Remax Wechat 演示",
    navigationBarBackgroundColor: "#F8F8F8",
    backgroundColor: "#F8F8F8"
  },
  tabBar: {
    color: "#7A7E83",
    selectedColor: "#3cc51f",
    borderStyle: "black",
    backgroundColor: "#ffffff",
    list: [
      {
        pagePath: "pages/component/index",
        iconPath: "image/icon_component.png",
        selectedIconPath: "image/icon_component_HL.png",
        text: "组件"
      },
      {
        pagePath: "pages/weui/index",
        iconPath: "image/icon_component.png",
        selectedIconPath: "image/icon_component_HL.png",
        text: "扩展组件"
      },
      {
        pagePath: "pages/api/index",
        iconPath: "image/icon_API.png",
        selectedIconPath: "image/icon_API_HL.png",
        text: "接口"
      },
      {
        pagePath: "pages/cloud/index",
        iconPath: "image/icon_cloud.png",
        selectedIconPath: "image/icon_cloud_HL.png",
        text: "云开发"
      }
    ]
  },
  networkTimeout: {
    request: 10000,
    connectSocket: 10000,
    uploadFile: 10000,
    downloadFile: 10000
  },
  debug: false,
  style: "v2",
  permission: {
    "scope.userLocation": {
      desc: "你的位置信息将用于小程序位置接口的效果展示"
    }
  },
  cloud: true
};
